### ISSUE TITLE
Add general use example to README

### ISSUE THREAD

**Issue by aerispaha** [aerispaha/trace#5]
Provide a simple example of how to use sewergraph in the osmnx branch README.

**Comment by aerispaha** [comment]
@nworbc5565, can you take a stab at this? Or can you reply here with a snippet from that Jupyter notebook script we were looking at?

**Comment by nworbc5565** [comment]
For sure @aerispaha. Working on fixing environmental variables this morning with Matt & Phil. Will post snippet later today when it's good to go.
